name: flutter_mov_app
description: App de Movimentações - login JWT, sync pendentes, assinatura e base local
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true
